### ISSUE TITLE
another good paper

### ISSUE THREAD

**Issue by zdx3578** [ago109/predictive-forward-forward#2]
https://github.com/NeuromorphicComputing/SoftHebb

**Comment by ago109** [comment]
I agree; though I think this issue should be raised on [the ngc-learn model museum repo](https://github.com/NACLab/ngc-museum) -- could you raise the issue with a link to the softhebb repo/paper there? 
That way the ngc-learn dev team can work on possibly implementing a softhebb model as an exhibit in the museum =) Many thanks!
